// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('gunslinger').directive('radial', function() {
    return {
      restrict: 'E',
      templateUrl: '../views/radial.html',
      scope: {
        radius: '=',
        lineWidth: '='
      },
      link: function(scope, element) {
        var bgColor, canvas, color, context, drawArc, getRadians, lineWidth, radius, xCoord, yCoord;
        bgColor = '#222';
        color = '#ff0000';
        canvas = angular.element(element).find('canvas').get(0);
        context = canvas.getContext('2d');
        lineWidth = scope.lineWidth ? scope.lineWidth : 10;
        xCoord = scope.radius;
        yCoord = scope.radius;
        radius = scope.radius - lineWidth;
        getRadians = function(degrees) {
          return degrees * Math.PI / 180;
        };
        drawArc = function(startingAngleInDegrees, endingAngleInDegrees, arcColor) {
          var endAngle, startAngle;
          context.beginPath();
          context.strokeStyle = arcColor;
          context.lineWidth = lineWidth;
          startAngle = getRadians(startingAngleInDegrees);
          endAngle = getRadians(endingAngleInDegrees);
          context.arc(xCoord, yCoord, radius, startAngle, endAngle);
          return context.stroke();
        };
        drawArc(-270, 90, bgColor);
        return drawArc(90, -210, color);
      }
    };
  });

}).call(this);
