// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('gunslinger').directive('radial', function() {
    return {
      restrict: 'E',
      templateUrl: 'templates/radial.html',
      scope: {
        width: '=',
        height: '=',
        radius: '=',
        lineWidth: '=',
        backgroundColor: '=',
        color: '='
      },
      link: function(scope, element) {
        var canvas, context, endingAngle, getRadians, height, lineWidth, radius, startingAngle, width;
        width = scope.width ? scope.width : 100;
        height = scope.width ? scope.width : 100;
        scope.width = width;
        scope.height = height;
        radius = scope.radius ? scope.radius : width / 2;
        lineWidth = scope.lineWidth ? scope.lineWidth : 10;
        startingAngle = 0;
        endingAngle = -270;
        canvas = angular.element(element).find('canvas').get(0);
        context = canvas.getContext('2d');
        getRadians = function(degrees) {
          return degrees * Math.PI / 180;
        };
        context.beginPath();
        context.strokeStyle = "#00ff00";
        context.lineWidth = lineWidth;
        context.arc(width, height, radius, startingAngle, endingAngle, Math.PI * 2);
        return context.stroke();
      }
    };
  });

}).call(this);
