// Generated by CoffeeScript 1.7.1
(function() {
  describe('gunslinger', function() {
    var module;
    module = null;
    return before(function() {
      return module = angular.module('gunslinger');
    });
  });

}).call(this);
