// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('gunslingr', ['ngRoute', 'firebase', 'ngAnimate', 'ngSanitize', 'ngCookies', 'mgcrea.ngStrap']).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: "views/home.html",
      controller: "homeCtrl"
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
