// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('gunslingr', ['ngRoute', 'ui.router', 'angularFileUpload', 'firebase', 'ngSanitize', 'mgcrea.ngStrap.modal']).config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');
    return $stateProvider.state('home', {
      url: "/",
      templateUrl: "views/home.html",
      controller: "homeCtrl"
    });
  });

}).call(this);
