// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('gunslingr', ['ngRoute', 'firebase', 'ngSanitize']).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: "views/home.html",
      controller: "homeCtrl"
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
