// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('gunslingr').controller('navigationCtrl', function($scope, firebase) {
    var defaults, loginAsideOptions;
    defaults = {
      facebook: {
        scope: 'email',
        rememberMe: true
      },
      github: {
        scope: 'user:email',
        rememberMe: true
      },
      twitter: {
        rememberMe: true
      }
    };
    loginAsideOptions = {
      scope: $scope,
      template: 'views/aside-login.html'
    };
    $scope.loginAside = function() {
      return $aside(loginAsideOptions);
    };
    firebase.auth.$getCurrentUser().then(function(user) {
      return $scope.user = user;
    });
    $scope.login = function(service) {
      switch (service) {
        case 'facebook':
          return firebase.auth.$login('facebook', defaults.facebook).then(function(user) {
            return $scope.user = user;
          });
        case 'github':
          return firebase.auth.$login('github', defaults.github).then(function(user) {
            return $scope.user = user;
          });
        case 'twitter':
          return firebase.auth.$login('twitter', defaults.twitter).then(function(user) {
            return $scope.user = user;
          });
      }
    };
    $scope.logout = function() {
      firebase.auth.$logout();
      return $scope.user = null;
    };
    return $scope.test = function() {
      return console.log('test', arguments);
    };
  });

}).call(this);
