// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('gunslingr').controller('navigationCtrl', function($scope, firebase, $cookies) {
    var defaults, getFacebookDetails, getGithubDetails;
    defaults = {
      facebook: {
        scope: 'email',
        rememberMe: true
      },
      github: {
        scope: 'user:email',
        rememberMe: true
      },
      twitter: {
        rememberMe: true
      }
    };
    $scope.aside = {
      title: "Account Crap",
      animation: 'am-fadeAndSlideLeft',
      template: 'views/aside-login.html',
      placement: 'right',
      backdrop: true
    };
    getFacebookDetails = function(user) {
      return {
        name: {
          first: user.first_name,
          last: user.last_name,
          display: user.displayName,
          user: user.username
        },
        email: user.email,
        id: user.id,
        url: user.profileUrl,
        gender: user.gender,
        pic: "http://graph.facebook.com/" + user.id + "/picture"
      };
    };
    getGithubDetails = function(user) {
      user = getFacebookDetails(user);
      user.pic = user.avatar_url;
      return user.name.full = user.name;
    };
    firebase.auth.$getCurrentUser().then(function(user) {
      console.log('user', user);
      $scope.user = user;
      return firebase.user($cookies.guid).$save(user);
    });
    $scope.login = function(service) {
      switch (service) {
        case 'facebook':
          return firebase.auth.$login('facebook', defaults.facebook).then(function(user) {
            return $scope.user = getFacebookDetails(user);
          });
        case 'github':
          return firebase.auth.$login('github', defaults.github).then(function(user) {
            return $scope.user = getGithubDetails(user);
          });
        case 'twitter':
          return firebase.auth.$login('twitter', defaults.twitter).then(function(user) {
            return $scope.user = getFacebookDetails(user);
          });
      }
    };
    return $scope.logout = function() {
      firebase.auth.$logout();
      return $scope.user = null;
    };
  });

}).call(this);
