// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('gunslingr').constant('config', function() {
    return {
      zencoder: {
        integration: '',
        read: '',
        full: ''
      },
      firebase: {
        "default": ''
      }
    };
  });

}).call(this);
