// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('gunslingr').service('firebase', function($firebase, $firebaseSimpleLogin, config) {
    return {
      auth: $firebaseSimpleLogin(new Firebase(config.firebase["default"])),
      playlists: $firebase(new Firebase(config.firebase.playlists)),
      uploads: $firebase(new Firebase(config.firebase.uploads)),
      users: $firebase(new Firebase(config.firebase.users)),
      user: function(guid) {
        console.log("" + config.firebase.users + "/" + guid);
        this.users.$save(guid);
        return $firebase(new Firebase("" + config.firebase.users + "/" + guid));
      }
    };
  });

}).call(this);
